#!/bin/bash
# Скрипт для удаления всех .md файлов кроме README.md

# Список файлов для удаления (кроме README.md)
files_to_delete=(
  "UPLOAD_TO_GITHUB.md"
  "GENERATE_YANDEX_CLIENT_README.md"
  "YANDEX_MARKET_OPENAPI_CLIENT.md"
  "FIX_BUILD_ERRORS.md"
  "PLAN.md"
  "GIT_SETUP.md"
  "GITHUB_UPLOAD.md"
  "DEPLOY_UPDATE.md"
  "QUICK_START.md"
  "FRONTEND_TROUBLESHOOTING.md"
  "NGINX_SETUP.md"
  "GIT_INIT_SERVER.md"
  "PM2_SETUP.md"
  "SETUP_DOMAIN.md"
  "QUICK_FIX_401.md"
  "FIX_COOKIES.md"
  "FIX_502_ERROR.md"
  "FIX_401_AUTH.md"
  "OZON_SYNC_README.md"
  "CHECK_COOKIES.md"
  "YANDEX_MARKET_INTEGRATION.md"
  "YANDEX_MARKET_SETUP.md"
  "README_YANDEX_MARKET.md"
  "PROJECT_IMPROVEMENTS.md"
  "YANDEX_MARKET_GO_SETUP.md"
  "GOOGLE_SHEETS_SETUP.md"
  "IMPROVEMENT_PLAN.md"
  "DEPLOY.md"
  "IMPROVEMENTS_SUMMARY.md"
  "IMAGE_OPTIMIZATION_SETUP.md"
  "FINAL_IMPROVEMENTS.md"
  "PROJECT_COMPLETION.md"
  "FINAL_COMPLETION_SUMMARY.md"
  "OZON_AUTO_SYNC_FIX.md"
  "QUICK_DEPLOY_GUIDE.md"
  "DEPLOY_PRODUCTION.md"
  "QUICK_GITHUB_UPLOAD.md"
  "GITHUB_UPLOAD_INSTRUCTIONS.md"
  "GITHUB_SETUP.md"
  "INSTALL_INSTRUCTIONS.md"
  "QUICK_DEPLOY_FROM_GITHUB.md"
  "FIX_TSC_ERROR.md"
  "DEPLOY_FROM_GITHUB.md"
  "FIX_MISSING_DEPENDENCIES.md"
  "FIX_MEMORY_ERROR.md"
  "FIX_INVOICES_MAP_ERROR.md"
  "FIX_DEBOUNCED_AND_BUSINESSES_ERRORS.md"
  "FIX_IMPORTING_ERROR.md"
  "FIX_TYPESCRIPT_ERRORS.md"
  "FIX_REMAINING_TYPESCRIPT_ERRORS.md"
  "QUICK_FIX_MONGODB.md"
  "FIX_MONGODB_CONNECTION.md"
  "FIX_MONGODB_AUTH.md"
  "FIX_NGINX_FRONTEND.md"
  "QUICK_FIX_NGINX.md"
  "FIX_MONGODB_UNAUTHORIZED.md"
  "FIX_COOKIE_AUTH.md"
  "SETUP_HTTPS.md"
  "QUICK_SETUP_HTTPS.md"
  "MONGODB_LOCAL_SETUP.md"
  "INSTALL_DEPENDENCIES.md"
)

echo "🗑️  Удаление лишних .md файлов..."
for file in "${files_to_delete[@]}"; do
  if [ -f "$file" ]; then
    echo "  Удаление: $file"
    git rm "$file" 2>/dev/null || rm -f "$file"
  fi
done

echo "✅ Готово!"

